"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { CheckCircle2,ClipboardCheck,Clock3,RefreshCw,Users } from "lucide-react";
import { FormFeedback } from "@/components/form-feedback";
import type { PortalUser } from "./auth-gate";

type AttendanceStatus=""|"present"|"late"|"absent"|"authorised";
type ClassRecord={id:string;name:string;programme:string;room?:string;dayOfWeek:number;startTime:string;endTime:string;capacity:number;active:boolean|number;teacherName?:string;enrolled:number};
type RegisterStudent={studentId:string;admissionNumber:string;fullName:string;attendanceId?:string;status:AttendanceStatus|null;checkInTime?:string|null;notes?:string|null;updatedAt?:string|null};
async function request<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{credentials:"same-origin",...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"The request could not be completed.");return data}
function localToday(){const now=new Date();return new Date(now.getTime()-now.getTimezoneOffset()*60_000).toISOString().slice(0,10)}
function normaliseStudents(students:RegisterStudent[]):RegisterStudent[]{return students.map(student=>({...student,status:student.status||"",checkInTime:student.checkInTime||"",notes:student.notes||""}))}

export function AttendanceView({user,query}:{user:PortalUser;query:string}){
 const [classes,setClasses]=useState<ClassRecord[]>([]),[classId,setClassId]=useState(""),[attendanceDate,setAttendanceDate]=useState(localToday),[students,setStudents]=useState<RegisterStudent[]>([]),[classesLoading,setClassesLoading]=useState(true),[registerLoading,setRegisterLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 useEffect(()=>{if(!success)return;const timer=window.setTimeout(()=>setSuccess(""),5000);return()=>window.clearTimeout(timer)},[success]);
 useEffect(()=>{request<{classes:ClassRecord[]}>("/api/portal/classes").then(result=>{const active=result.classes.filter(item=>Boolean(item.active));setClasses(active);setClassId(current=>active.some(item=>item.id===current)?current:active[0]?.id||"");if(active.length===0)setRegisterLoading(false)}).catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load classes.")).finally(()=>setClassesLoading(false))},[]);
 const loadRegister=useCallback(async()=>{if(!classId){setStudents([]);return}setRegisterLoading(true);setError("");setSuccess("");try{const result=await request<{students:RegisterStudent[]}>(`/api/portal/attendance?classId=${encodeURIComponent(classId)}&date=${encodeURIComponent(attendanceDate)}`);setStudents(normaliseStudents(result.students))}catch(reason){setStudents([]);setError(reason instanceof Error?reason.message:"Unable to load the attendance register.")}finally{setRegisterLoading(false)}},[classId,attendanceDate]);
 useEffect(()=>{if(!classId)return;let active=true;request<{students:RegisterStudent[]}>(`/api/portal/attendance?classId=${encodeURIComponent(classId)}&date=${encodeURIComponent(attendanceDate)}`).then(result=>{if(active)setStudents(normaliseStudents(result.students))}).catch(reason=>{if(active){setStudents([]);setError(reason instanceof Error?reason.message:"Unable to load the attendance register.")}}).finally(()=>{if(active)setRegisterLoading(false)});return()=>{active=false}},[classId,attendanceDate]);
 const selectedClass=classes.find(item=>item.id===classId),filtered=students.filter(student=>!query||`${student.fullName} ${student.admissionNumber}`.toLowerCase().includes(query.toLowerCase()));
 const counts=useMemo(()=>students.reduce((result,student)=>{if(student.status)result[student.status]+=1;else result.unmarked+=1;return result},{present:0,late:0,absent:0,authorised:0,unmarked:0}),[students]);
 function updateStudent(studentId:string,changes:Partial<RegisterStudent>){setError("");setSuccess("");setStudents(current=>current.map(student=>student.studentId===studentId?{...student,...changes}:student))}
 function updateStatus(studentId:string,status:AttendanceStatus){updateStudent(studentId,{status,...(status==="absent"||status==="authorised"?{checkInTime:""}:{})})}
 async function saveRegister(event:FormEvent<HTMLFormElement>){event.preventDefault();if(counts.unmarked>0){setError(`Mark all ${counts.unmarked} remaining ${counts.unmarked===1?"pupil":"pupils"} before saving the register.`);requestAnimationFrame(()=>document.querySelector<HTMLSelectElement>('.register-status-select[data-unmarked="true"]')?.focus());return}setSaving(true);setError("");setSuccess("");try{await request("/api/portal/attendance",{method:"POST",body:JSON.stringify({classId,attendanceDate,entries:students.map(student=>({studentId:student.studentId,status:student.status,checkInTime:student.checkInTime,notes:student.notes}))})});await loadRegister();setSuccess(`Attendance saved for ${students.length} ${students.length===1?"pupil":"pupils"} in ${selectedClass?.name||"this class"}.`)}catch(reason){setError(reason instanceof Error?reason.message:"Unable to save attendance. Your entries have been retained.")}finally{setSaving(false)}}
 if(user.role!=="admin"&&user.role!=="teacher")return <div className="live-empty"><ClipboardCheck/><h3>Teaching access required</h3><p>Your account does not have permission to view or record attendance.</p></div>;
 return <section className="panel live-records register-module">
  <div className="records-toolbar"><div><h3>Class attendance</h3><p>Open a class register, record attendance and safely amend saved entries.</p></div><button className="secondary" type="button" onClick={()=>void loadRegister()} disabled={!classId||registerLoading}><RefreshCw size={16}/>Refresh</button></div>
  <div className="register-controls"><label>Class<select value={classId} onChange={event=>{setRegisterLoading(true);setError("");setSuccess("");setClassId(event.target.value)}} disabled={classesLoading}><option value="">Select a class</option>{classes.map(item=><option key={item.id} value={item.id}>{item.name} ({item.enrolled} enrolled)</option>)}</select></label><label>Attendance date<input type="date" value={attendanceDate} max={localToday()} onChange={event=>{setRegisterLoading(true);setError("");setSuccess("");setAttendanceDate(event.target.value)}}/></label><div className="register-class-meta"><span>{selectedClass?.programme||"Select a teaching group"}</span><strong>{selectedClass?`${selectedClass.startTime}–${selectedClass.endTime}${selectedClass.room?` · ${selectedClass.room}`:""}`:"The enrolled pupils will appear below."}</strong></div></div>
  <FormFeedback id="attendance-error" message={error}/><FormFeedback message={success} tone="success"/>
  {classesLoading||registerLoading?<div className="live-loading"><RefreshCw className="spin"/>Loading register…</div>:!classId?<div className="live-empty"><ClipboardCheck/><h3>No class selected</h3><p>Select a class and date to open its attendance register.</p></div>:students.length===0?<div className="live-empty"><Users/><h3>No pupils on this register</h3><p>Enrol a pupil in {selectedClass?.name||"this class"} before recording attendance.</p></div>:<form onSubmit={saveRegister}>
   <div className="register-summary" aria-label="Attendance totals"><div><CheckCircle2/><span>Present<strong>{counts.present}</strong></span></div><div><Clock3/><span>Late<strong>{counts.late}</strong></span></div><div><span className="register-summary-dot absent"/><span>Absent<strong>{counts.absent}</strong></span></div><div><span className="register-summary-dot authorised"/><span>Authorised<strong>{counts.authorised}</strong></span></div><div><span className="register-summary-dot unmarked"/><span>Unmarked<strong>{counts.unmarked}</strong></span></div></div>
   <div className="register-actions-top"><p>{students.length-counts.unmarked} of {students.length} pupils marked</p><button className="secondary" type="button" onClick={()=>{setStudents(current=>current.map(student=>({...student,status:"present"})));setError("");setSuccess("")}}>Mark all present</button></div>
   {filtered.length===0?<div className="live-empty register-filter-empty"><Users/><h3>No matching pupils</h3><p>Clear the portal search to see the full class register.</p></div>:<div className="register-list"><div className="register-list-head" aria-hidden="true"><span>Pupil</span><span>Status</span><span>Check-in</span><span>Notes</span></div>{filtered.map(student=><article className={`register-row status-${student.status||"unmarked"}`} key={student.studentId}><div className="register-student"><span>{student.fullName.split(/\s+/).map(part=>part[0]).slice(0,2).join("").toUpperCase()}</span><div><strong>{student.fullName}</strong><small>{student.admissionNumber}</small></div></div><label><span>Status</span><select className="register-status-select" data-unmarked={!student.status} value={student.status||""} onChange={event=>updateStatus(student.studentId,event.target.value as AttendanceStatus)} aria-label={`Attendance status for ${student.fullName}`}><option value="">Not marked</option><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="authorised">Authorised absence</option></select></label><label><span>Check-in</span><input type="time" value={student.checkInTime||""} disabled={student.status==="absent"||student.status==="authorised"||!student.status} onChange={event=>updateStudent(student.studentId,{checkInTime:event.target.value})} aria-label={`Check-in time for ${student.fullName}`}/></label><label><span>Notes</span><input type="text" value={student.notes||""} maxLength={500} placeholder="Optional note" onChange={event=>updateStudent(student.studentId,{notes:event.target.value})} aria-label={`Attendance note for ${student.fullName}`}/></label></article>)}</div>}
   <div className="register-savebar"><p>{counts.unmarked?`${counts.unmarked} ${counts.unmarked===1?"pupil remains":"pupils remain"} unmarked.`:"The register is complete and ready to save."}</p><button className="primary" disabled={saving}>{saving?"Saving register…":"Save attendance"}</button></div>
  </form>}
 </section>
}
