"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { Megaphone,Plus,RefreshCw,ShieldAlert,X } from "lucide-react";
import { FormFeedback } from "@/components/form-feedback";
import type { PortalUser } from "./auth-gate";
import { displayDate,portalApi } from "./portal-api";
type Announcement={id:string;title:string;body:string;audience:string;publishedAt:string;expiresAt?:string;publishedBy?:string};
type EmailDelivery={status:"sent"|"partial"|"failed"|"not_configured"|"no_recipients"|"not_applicable";recipients:number;sent:number};
export function AnnouncementsView({user,query}:{user:PortalUser;query:string}){
 const [items,setItems]=useState<Announcement[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[formError,setFormError]=useState(""),[success,setSuccess]=useState(""),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!success)return;const timer=window.setTimeout(()=>setSuccess(""),5000);return()=>window.clearTimeout(timer)},[success]);
 const load=useCallback(()=>{setLoading(true);setError("");portalApi<{announcements:Announcement[]}>("/api/portal/announcements").then(result=>setItems(result.announcements)).catch(cause=>setError(cause instanceof Error?cause.message:"Unable to load announcements.")).finally(()=>setLoading(false))},[]);useEffect(()=>{let active=true;portalApi<{announcements:Announcement[]}>("/api/portal/announcements").then(result=>{if(active)setItems(result.announcements)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load announcements.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function publish(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setFormError("");try{const result=await portalApi<{emailDelivery:EmailDelivery}>("/api/portal/announcements",{method:"POST",body:JSON.stringify(Object.fromEntries(form))});setShowForm(false);setSuccess(deliveryMessage(result.emailDelivery));load()}catch(cause){setFormError(cause instanceof Error?cause.message:"Unable to publish the announcement.")}finally{setBusy(false)}}
 const filtered=items.filter(item=>!query||`${item.title} ${item.body} ${item.audience}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="panel live-records operations-module"><div className="records-toolbar"><div><h3>Announcements</h3><p>Important Madrasat updates for staff and families.</p></div><div className="toolbar-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button>{user.role==="admin"&&<button className="primary" onClick={()=>{setFormError("");setShowForm(true)}}><Plus size={16}/>Publish</button>}</div></div>{error&&<div className="live-error">{error}</div>}<FormFeedback message={success} tone="success"/>{loading?<div className="live-loading"><RefreshCw className="spin"/>Loading announcements…</div>:filtered.length===0?<div className="live-empty"><Megaphone/><h3>No announcements</h3><p>Published notices for your account will appear here.</p></div>:<div className="announcement-list">{filtered.map(item=><article key={item.id}><div className="announcement-icon"><Megaphone/></div><div><span className="eyebrow">{item.audience} · {displayDate(item.publishedAt)}</span><h3>{item.title}</h3><p>{item.body}</p><small>Published by {item.publishedBy||"Al-Hidaya"}{item.expiresAt?` · Expires ${displayDate(item.expiresAt)}`:""}</small></div></article>)}</div>}
  {showForm&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>!busy&&setShowForm(false)} disabled={busy} aria-label="Close announcement form"><X/></button><div className="modal-icon"><Megaphone/></div><h2>Publish announcement</h2><p>The notice becomes visible immediately in the selected users’ portal. Parent and Everyone notices are also emailed privately to guardians of actively enrolled pupils.</p><FormFeedback id="announcement-error" message={formError}/><form onSubmit={publish} onChange={()=>formError&&setFormError("")}><label>Title<input name="title" maxLength={160} required/></label><label>Audience<select name="audience" defaultValue="all"><option value="all">Everyone</option><option value="parents">Parents only</option><option value="staff">Staff only</option></select></label><label>Message<textarea name="body" rows={6} maxLength={3000} required/></label><label>Expiry date (optional)<input name="expiresAt" type="date"/></label><div className="modal-actions"><button className="secondary" type="button" onClick={()=>setShowForm(false)} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?"Publishing…":"Publish announcement"}</button></div></form></div></div>}
 </section>
}

function deliveryMessage(delivery:EmailDelivery){
 if(delivery.status==="sent")return `Announcement published and emailed to ${delivery.sent} parent or guardian${delivery.sent===1?"":"s"}.`;
 if(delivery.status==="partial")return `Announcement published in the portal. Email reached ${delivery.sent} of ${delivery.recipients} parent or guardian recipients.`;
 if(delivery.status==="failed")return "Announcement published in the portal, but parent email delivery failed. Parents can still read it after signing in.";
 if(delivery.status==="not_configured")return "Announcement published in the portal. Parent email delivery is not configured in this environment.";
 if(delivery.status==="no_recipients")return "Announcement published in the portal. No actively enrolled guardian email recipients were found.";
 return "Announcement published for staff.";
}

type Case={id:string;studentId?:string;studentName?:string;admissionNumber?:string;concernType:string;summary:string;status:string;createdAt:string;updatedAt:string;reportedBy:string;assignedTo?:string;assignedToId?:string};
type Staff={id:string;fullName:string;role:string};type Student={id:string;fullName:string;admissionNumber:string};
export function SafeguardingView({user,query}:{user:PortalUser;query:string}){
 const [items,setItems]=useState<Case[]>([]),[staff,setStaff]=useState<Staff[]>([]),[students,setStudents]=useState<Student[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[formError,setFormError]=useState(""),[rowError,setRowError]=useState<Record<string,string>>({}),[success,setSuccess]=useState(""),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState("");
 useEffect(()=>{if(!success)return;const timer=window.setTimeout(()=>setSuccess(""),5000);return()=>window.clearTimeout(timer)},[success]);
 const load=useCallback(()=>{setLoading(true);setError("");Promise.all([portalApi<{cases:Case[];staff:Staff[]}>("/api/portal/safeguarding"),portalApi<{students:Student[]}>("/api/portal/students")]).then(([result,pupils])=>{setItems(result.cases);setStaff(result.staff);setStudents(pupils.students)}).catch(cause=>setError(cause instanceof Error?cause.message:"Unable to load safeguarding records.")).finally(()=>setLoading(false))},[]);useEffect(()=>{let active=true;Promise.all([portalApi<{cases:Case[];staff:Staff[]}>("/api/portal/safeguarding"),portalApi<{students:Student[]}>("/api/portal/students")]).then(([result,pupils])=>{if(active){setItems(result.cases);setStaff(result.staff);setStudents(pupils.students)}}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load safeguarding records.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function report(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy("create");setFormError("");try{await portalApi("/api/portal/safeguarding",{method:"POST",body:JSON.stringify(Object.fromEntries(form))});setShowForm(false);setSuccess("The safeguarding concern was recorded securely.");load()}catch(cause){setFormError(cause instanceof Error?cause.message:"Unable to record the concern.")}finally{setBusy("")}}
 async function update(item:Case,status:string,assignedTo:string){setBusy(item.id);setRowError(value=>({...value,[item.id]:""}));try{await portalApi(`/api/portal/safeguarding/${item.id}`,{method:"PATCH",body:JSON.stringify({status,assignedTo})});setItems(current=>current.map(entry=>entry.id===item.id?{...entry,status,assignedToId:assignedTo,assignedTo:staff.find(person=>person.id===assignedTo)?.fullName}:entry));setSuccess("Safeguarding case updated securely.")}catch(cause){setRowError(value=>({...value,[item.id]:cause instanceof Error?cause.message:"Unable to update the case."}))}finally{setBusy("")}}
 const filtered=items.filter(item=>!query||`${item.studentName} ${item.concernType} ${item.summary} ${item.status}`.toLowerCase().includes(query.toLowerCase()));
 return <section className="panel live-records operations-module safeguarding-module"><div className="records-toolbar"><div><h3>Safeguarding concerns</h3><p>Restricted records. Share only factual information necessary to protect the child.</p></div><div className="toolbar-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button><button className="primary" onClick={()=>{setFormError("");setShowForm(true)}}><Plus size={16}/>Report concern</button></div></div><div className="privacy-banner"><ShieldAlert/><span><strong>Confidential safeguarding information</strong>Access and changes are recorded in the audit log.</span></div>{error&&<div className="live-error">{error}</div>}<FormFeedback message={success} tone="success"/>{loading?<div className="live-loading"><RefreshCw className="spin"/>Loading restricted records…</div>:filtered.length===0?<div className="live-empty"><ShieldAlert/><h3>No safeguarding cases found</h3><p>New concerns reported or assigned to you will appear here.</p></div>:<div className="operation-cards">{filtered.map(item=><article key={item.id}><div className="operation-card-head"><div><span className="eyebrow">{item.concernType}</span><h3>{item.studentName||"General concern"}</h3><p>{item.admissionNumber||"No pupil linked"} · Reported {displayDate(item.createdAt)}</p></div><span className={`record-status status-${item.status}`}>{item.status}</span></div><p className="case-summary">{item.summary}</p><dl><div><dt>Reported by</dt><dd>{item.reportedBy}</dd></div><div><dt>Assigned to</dt><dd>{item.assignedTo||"Unassigned"}</dd></div></dl>{user.role==="admin"&&<div className="case-controls"><select value={item.status} disabled={busy===item.id} onChange={event=>update(item,event.target.value,item.assignedToId||"")} aria-label={`Status for ${item.concernType}`}><option value="open">Open</option><option value="monitoring">Monitoring</option><option value="referred">Referred</option><option value="closed">Closed</option></select><select value={item.assignedToId||""} disabled={busy===item.id} onChange={event=>update(item,item.status,event.target.value)} aria-label={`Assignee for ${item.concernType}`}><option value="">Unassigned</option>{staff.map(person=><option key={person.id} value={person.id}>{person.fullName}</option>)}</select></div>}<FormFeedback message={rowError[item.id]||""}/></article>)}</div>}
  {showForm&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>!busy&&setShowForm(false)} disabled={Boolean(busy)} aria-label="Close safeguarding form"><X/></button><div className="modal-icon"><ShieldAlert/></div><h2>Report safeguarding concern</h2><p>Record observations factually. For an immediate danger, follow the mosque’s emergency safeguarding procedure first.</p><FormFeedback id="safeguarding-error" message={formError}/><form onSubmit={report} onChange={()=>formError&&setFormError("")}><label>Pupil (optional)<select name="studentId" defaultValue=""><option value="">General or pupil not listed</option>{students.map(student=><option key={student.id} value={student.id}>{student.fullName} ({student.admissionNumber})</option>)}</select></label><label>Concern type<input name="concernType" required placeholder="e.g. Welfare disclosure"/></label><label>Factual summary<textarea name="summary" rows={7} maxLength={3000} required/></label>{user.role==="admin"&&<label>Assign to<select name="assignedTo" defaultValue=""><option value="">Unassigned</option>{staff.map(person=><option key={person.id} value={person.id}>{person.fullName}</option>)}</select></label>}<div className="modal-actions"><button className="secondary" type="button" onClick={()=>setShowForm(false)} disabled={Boolean(busy)}>Cancel</button><button className="primary" disabled={Boolean(busy)}>{busy?"Recording…":"Record securely"}</button></div></form></div></div>}
 </section>
}
