"use client";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { CreditCard,Plus,ReceiptText,RefreshCw,WalletCards,X } from "lucide-react";
import { FormFeedback } from "@/components/form-feedback";
import type { PortalUser } from "./auth-gate";
import { displayDate,localToday,money,portalApi } from "./portal-api";
type Fee={id:string;studentId:string;admissionNumber:string;studentName:string;term:string;amountDuePence:number;amountPaidPence:number;balancePence:number;dueDate:string;status:string;guardianName?:string};
type Payment={id:string;feeAccountId:string;amountPence:number;paidAt:string;method:string;reference?:string;recordedBy?:string};
type Student={id:string;admissionNumber:string;fullName:string};
type FeeResponse={accounts:Fee[];payments:Payment[];summary:{due:number;paid:number;balance:number;overdue:number}};
export function FeesView({user,query}:{user:PortalUser;query:string}){
 const [data,setData]=useState<FeeResponse>({accounts:[],payments:[],summary:{due:0,paid:0,balance:0,overdue:0}}),[students,setStudents]=useState<Student[]>([]),[loading,setLoading]=useState(true),[pageError,setPageError]=useState(""),[formError,setFormError]=useState(""),[success,setSuccess]=useState(""),[busy,setBusy]=useState(false),[showFee,setShowFee]=useState(false),[paymentFor,setPaymentFor]=useState<Fee|null>(null);
 const canManage=user.role==="admin"||user.role==="finance";
 useEffect(()=>{if(!success)return;const timer=window.setTimeout(()=>setSuccess(""),5000);return()=>window.clearTimeout(timer)},[success]);
 const load=useCallback(()=>{setLoading(true);setPageError("");Promise.all([portalApi<FeeResponse>("/api/portal/fees"),canManage?portalApi<{students:Student[]}>("/api/portal/students"):Promise.resolve({students:[]})]).then(([fees,pupils])=>{setData(fees);setStudents(pupils.students)}).catch(cause=>setPageError(cause instanceof Error?cause.message:"Unable to load fees.")).finally(()=>setLoading(false))},[canManage]);
 useEffect(()=>{let active=true;Promise.all([portalApi<FeeResponse>("/api/portal/fees"),canManage?portalApi<{students:Student[]}>("/api/portal/students"):Promise.resolve({students:[]})]).then(([fees,pupils])=>{if(active){setData(fees);setStudents(pupils.students)}}).catch(cause=>{if(active)setPageError(cause instanceof Error?cause.message:"Unable to load fees.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[canManage]);
 async function createFee(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setFormError("");try{await portalApi("/api/portal/fees",{method:"POST",body:JSON.stringify(Object.fromEntries(form))});setShowFee(false);setSuccess("The fee account was created successfully.");load()}catch(cause){setFormError(cause instanceof Error?cause.message:"Unable to create the fee account.")}finally{setBusy(false)}}
 async function recordPayment(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!paymentFor)return;const form=new FormData(event.currentTarget);setBusy(true);setFormError("");try{await portalApi(`/api/portal/fees/${paymentFor.id}/payments`,{method:"POST",body:JSON.stringify(Object.fromEntries(form))});setPaymentFor(null);setSuccess(`Payment recorded successfully for ${paymentFor.studentName}.`);load()}catch(cause){setFormError(cause instanceof Error?cause.message:"Unable to record the payment.")}finally{setBusy(false)}}
 const filtered=data.accounts.filter(item=>!query||`${item.studentName} ${item.admissionNumber} ${item.term} ${item.status}`.toLowerCase().includes(query.toLowerCase()));
 const paymentsByAccount=useMemo(()=>data.payments.reduce<Record<string,Payment[]>>((result,item)=>{(result[item.feeAccountId]??=[]).push(item);return result},{}),[data.payments]);
 return <section className="panel live-records operations-module"><div className="records-toolbar"><div><h3>Fees and payments</h3><p>{canManage?"Create pupil fee accounts and record verified payments.":"View fee accounts and payments for your children."}</p></div><div className="toolbar-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button>{canManage&&<button className="primary" onClick={()=>{setFormError("");setShowFee(true)}}><Plus size={16}/>New fee</button>}</div></div>{pageError&&<div className="live-error">{pageError}</div>}<FormFeedback message={success} tone="success"/>
  <div className="operations-stats"><article><span>Fees raised</span><strong>{money(data.summary.due)}</strong></article><article><span>Payments received</span><strong>{money(data.summary.paid)}</strong></article><article><span>Outstanding</span><strong>{money(data.summary.balance)}</strong></article><article><span>Overdue accounts</span><strong>{data.summary.overdue}</strong></article></div>
  {loading?<div className="live-loading"><RefreshCw className="spin"/>Loading fee accounts…</div>:filtered.length===0?<div className="live-empty"><WalletCards/><h3>No fee accounts found</h3><p>{canManage?"Create the first fee account for an enrolled pupil.":"There are no fees linked to your parent account."}</p></div>:<div className="operation-cards">{filtered.map(account=><article key={account.id}><div className="operation-card-head"><div><span className="eyebrow">{account.admissionNumber} · {account.term}</span><h3>{account.studentName}</h3><p>Due {displayDate(account.dueDate)}</p></div><span className={`record-status status-${account.status}`}>{account.status.replace("_"," ")}</span></div><div className="fee-progress"><div><span>Paid</span><strong>{money(account.amountPaidPence)} of {money(account.amountDuePence)}</strong></div><progress value={account.amountPaidPence} max={account.amountDuePence}/><b>{money(account.balancePence)} remaining</b></div>{(paymentsByAccount[account.id]||[]).slice(0,3).map(payment=><div className="payment-line" key={payment.id}><ReceiptText/><span><strong>{money(payment.amountPence)}</strong>{displayDate(payment.paidAt)} · {payment.method.replace("_"," ")}{payment.reference?` · ${payment.reference}`:""}</span></div>)}{canManage&&account.balancePence>0&&account.status!=="waived"&&<button className="secondary card-action" onClick={()=>{setFormError("");setPaymentFor(account)}}><CreditCard size={16}/>Record payment</button>}</article>)}</div>}
  {showFee&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>!busy&&setShowFee(false)} disabled={busy} aria-label="Close fee form"><X/></button><div className="modal-icon"><WalletCards/></div><h2>Create fee account</h2><p>Add the amount due for one pupil and term. Duplicate pupil/term accounts are prevented.</p><FormFeedback id="fee-form-error" message={formError}/><form onSubmit={createFee} onChange={()=>formError&&setFormError("")}><label>Pupil<select name="studentId" required defaultValue=""><option value="" disabled>Select an enrolled pupil</option>{students.map(student=><option key={student.id} value={student.id}>{student.fullName} ({student.admissionNumber})</option>)}</select></label><label>Term or fee period<input name="term" required placeholder="e.g. Autumn 2026"/></label><div className="form-grid"><label>Amount due (£)<input name="amount" type="number" min="0.01" step="0.01" inputMode="decimal" required/></label><label>Due date<input name="dueDate" type="date"/></label></div><div className="modal-actions"><button className="secondary" type="button" onClick={()=>setShowFee(false)} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?"Creating…":"Create fee"}</button></div></form></div></div>}
  {paymentFor&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>!busy&&setPaymentFor(null)} disabled={busy} aria-label="Close payment form"><X/></button><div className="modal-icon"><CreditCard/></div><h2>Record payment</h2><p>{paymentFor.studentName} · {paymentFor.term} · {money(paymentFor.balancePence)} outstanding</p><FormFeedback id="payment-form-error" message={formError}/><form onSubmit={recordPayment} onChange={()=>formError&&setFormError("")}><div className="form-grid"><label>Amount (£)<input name="amount" type="number" min="0.01" max={(paymentFor.balancePence/100).toFixed(2)} step="0.01" required/></label><label>Payment date<input name="paidAt" type="date" max={localToday()} defaultValue={localToday()} required/></label></div><label>Payment method<select name="method" defaultValue="bank_transfer" required><option value="bank_transfer">Bank transfer</option><option value="cash">Cash</option><option value="card">Card</option><option value="online">Online payment</option><option value="other">Other</option></select></label><label>Reference<input name="reference" placeholder="Optional unique reference"/></label><div className="modal-actions"><button className="secondary" type="button" onClick={()=>setPaymentFor(null)} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?"Recording…":"Record payment"}</button></div></form></div></div>}
 </section>
}
