"use client";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { BookOpen, ClipboardCheck, FileText, GraduationCap, LoaderCircle, Megaphone, Plus, RefreshCw, Users, WalletCards, X } from "lucide-react";
import type { PortalUser } from "./auth-gate";
import { FormFeedback } from "@/components/form-feedback";
import { AttendanceView } from "./attendance-view";
import { FeesView } from "./fees-view";
import { StaffView } from "./staff-view";
import { AnnouncementsView, SafeguardingView } from "./communications-view";
import { ReportsView } from "./reports-view";
import { SettingsView } from "./settings-view";
import { ParentAttendanceView } from "./parent-attendance-view";

type Application={id:string;childName:string;dateOfBirth:string;gender:string;programme:string;guardianName:string;guardianEmail:string;guardianPhone:string;address:string;postcode:string;notes?:string;status:string;createdAt:string};
type Student={id:string;admissionNumber:string;fullName:string;dateOfBirth:string;gender:string;status:string;guardianName?:string;guardianEmail?:string;guardianPhone?:string;className?:string};
type ClassRecord={id:string;name:string;programme:string;room?:string;dayOfWeek:number;startTime:string;endTime:string;capacity:number;active:boolean|number;teacherName?:string;enrolled:number};
type Summary={role:string;metrics:Array<{label:string;value:number;format?:string;target:string}>};

async function api<T>(url:string,init?:RequestInit):Promise<T>{const response=await fetch(url,{credentials:"same-origin",...init,headers:{"Content-Type":"application/json",...(init?.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||"The request could not be completed.");return data}
function ErrorNotice({message}:{message:string}){return <div className="live-error" role="alert">{message}</div>}
function Empty({icon:Icon,title,text}:{icon:typeof FileText;title:string;text:string}){return <div className="live-empty"><Icon/><h3>{title}</h3><p>{text}</p></div>}
function Loading(){return <div className="live-loading"><LoaderCircle className="spin"/>Loading records…</div>}
function date(value:string){return new Intl.DateTimeFormat("en-GB",{day:"numeric",month:"short",year:"numeric"}).format(new Date(value))}

export function OverviewView({user,onNavigate}:{user:PortalUser;onNavigate:(section:string)=>void}){
 const [summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState("");
 useEffect(()=>{api<Summary>("/api/portal/summary").then(setSummary).catch(e=>setError(e.message))},[]);
 const icons:Record<string,typeof FileText>={Students:GraduationCap,Applications:FileText,Classes:BookOpen,Attendance:ClipboardCheck,Fees:WalletCards,Announcements:Megaphone,Safeguarding:FileText};const tones=["gold","blue","green","purple"];
 return <>{error&&<ErrorNotice message={error}/>}<section className="stats live-stats">{(summary?.metrics||[]).map((metric,index)=>{const Icon=icons[metric.target]||Users;return <button className="stat-button" key={metric.label} onClick={()=>onNavigate(metric.target)}><div className={`stat-icon ${tones[index%tones.length]}`}><Icon size={20}/></div><p>{metric.label}</p><h2>{metric.format==="money"?new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP"}).format(metric.value/100):metric.value}</h2><span>View records</span></button>})}</section>{user.role==="admin"?<section className="panel workflow-panel"><div><span className="eyebrow">Admissions workflow</span><h3>From application to first class</h3><p>Review each application, update its status, then enrol an accepted child into an available class. The student, guardian and enrolment records are created together.</p></div><ol><li><b>1</b><span><strong>Review</strong>Check the child and guardian details.</span></li><li><b>2</b><span><strong>Decide</strong>Offer, waitlist or decline the application.</span></li><li><b>3</b><span><strong>Enrol</strong>Select a class and generate an admission number.</span></li></ol><button className="primary" onClick={()=>onNavigate("Applications")}>Review applications</button></section>:<section className="panel workflow-panel role-workflow"><div><span className="eyebrow">Secure workspace</span><h3>{user.role==="parent"?"Your family’s Madrasah information":user.role==="teacher"?"Your teaching responsibilities":"Fees and financial records"}</h3><p>{user.role==="parent"?"View your children’s details, attendance, fees and Madrasah announcements in one place.":user.role==="teacher"?"Open assigned class registers, view your pupils and report safeguarding concerns securely.":"Create fee accounts, record verified payments and download financial reports."}</p></div><button className="primary" onClick={()=>onNavigate(user.role==="teacher"?"Attendance":"Fees")}>{user.role==="teacher"?"Open attendance":"View fees"}</button></section>}</>;
}

export function LiveRecords({section,user,query,onLogout}:{section:string;user:PortalUser;query:string;onLogout:()=>Promise<void>}){
 if(section==="Applications")return user.role==="admin"?<ApplicationsView query={query}/>:<NoAccess/>;
 if(section==="Students")return <StudentsView query={query}/>;
 if(section==="Classes")return <ClassesView user={user} query={query}/>;
 if(section==="Attendance")return user.role==="parent"?<ParentAttendanceView query={query}/>:<AttendanceView user={user} query={query}/>;
 if(section==="Fees")return <FeesView user={user} query={query}/>;
 if(section==="Announcements")return <AnnouncementsView user={user} query={query}/>;
 if(section==="Staff")return <StaffView user={user} query={query}/>;
 if(section==="Safeguarding")return <SafeguardingView user={user} query={query}/>;
 if(section==="Reports")return <ReportsView user={user}/>;
 if(section==="Settings")return <SettingsView user={user} onLogout={onLogout}/>;
 return <Empty icon={BookOpen} title={`${section} backend is next`} text="This module will be connected after the admissions and enrolment workflow has been confirmed."/>;
}

function ApplicationsView({query}:{query:string}){
 const [items,setItems]=useState<Application[]>([]),[classes,setClasses]=useState<ClassRecord[]>([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[rowErrors,setRowErrors]=useState<Record<string,string>>({}),[enrolError,setEnrolError]=useState(""),[busy,setBusy]=useState(""),[selected,setSelected]=useState<Application|null>(null),[success,setSuccess]=useState("");
 const load=useCallback(()=>{setLoading(true);setLoadError("");Promise.all([api<{applications:Application[]}>("/api/portal/applications"),api<{classes:ClassRecord[]}>("/api/portal/classes")]).then(([a,c])=>{setItems(a.applications);setClasses(c.classes.filter(x=>Boolean(x.active)&&Number(x.enrolled)<Number(x.capacity)))}).catch(e=>setLoadError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{Promise.all([api<{applications:Application[]}>("/api/portal/applications"),api<{classes:ClassRecord[]}>("/api/portal/classes")]).then(([a,c])=>{setItems(a.applications);setClasses(c.classes.filter(x=>Boolean(x.active)&&Number(x.enrolled)<Number(x.capacity)))}).catch(e=>setLoadError(e.message)).finally(()=>setLoading(false))},[]);
 function showSuccess(message:string){setSuccess(message);window.setTimeout(()=>setSuccess(""),5000)}
 function focusField(form:HTMLFormElement,name:string){requestAnimationFrame(()=>{const field=form.elements.namedItem(name);if(field instanceof HTMLElement)field.focus()})}
 function closeEnrolment(){if(busy)return;setSelected(null);setEnrolError("")}
 async function updateStatus(id:string,status:string){
  setBusy(id);setRowErrors(v=>({...v,[id]:""}));
  try{await api(`/api/portal/applications/${id}`,{method:"PATCH",body:JSON.stringify({status})});const child=items.find(x=>x.id===id)?.childName||"Application";setItems(v=>v.map(x=>x.id===id?{...x,status}:x));showSuccess(`${child}'s application status was updated to ${status}.`)}
  catch(e){setRowErrors(v=>({...v,[id]:e instanceof Error?e.message:"Unable to update application."}))}
  finally{setBusy("")}
 }
 async function enrol(event:FormEvent<HTMLFormElement>){
  event.preventDefault();if(!selected)return;const element=event.currentTarget;const data=new FormData(element);const classId=String(data.get("classId")||"");
  if(!classId){setEnrolError("Select an available class before confirming enrolment.");focusField(element,"classId");return}
  setBusy(selected.id);setEnrolError("");
  try{const result=await api<{admissionNumber:string;className:string}>(`/api/portal/applications/${selected.id}/enrol`,{method:"POST",body:JSON.stringify({classId,relationship:data.get("relationship")})});showSuccess(`${selected.childName} has been enrolled in ${result.className}. Admission number: ${result.admissionNumber}`);setItems(v=>v.map(x=>x.id===selected.id?{...x,status:"enrolled"}:x));setSelected(null)}
  catch(e){const message=e instanceof Error?e.message:"Unable to enrol child.";setEnrolError(message);if(message.toLowerCase().includes("class"))focusField(element,"classId")}
  finally{setBusy("")}
 }
 const filtered=items.filter(x=>!query||Object.values(x).join(" ").toLowerCase().includes(query.toLowerCase()));
 return <section className="panel live-records"><div className="records-toolbar"><div><h3>Admission applications</h3><p>Review applications and convert accepted children into enrolled students.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div>{loadError&&<ErrorNotice message={loadError}/>}<FormFeedback message={success} tone="success"/>{loading?<Loading/>:filtered.length===0?<Empty icon={FileText} title="No applications found" text="New public applications will appear here automatically."/>:<div className="record-cards">{filtered.map(item=><article key={item.id}><div className="record-card-head"><div><span className="eyebrow">{item.programme}</span><h3>{item.childName}</h3><p>{item.gender} · Born {date(item.dateOfBirth)}</p></div><span className={`record-status status-${item.status}`}>{item.status}</span></div><dl><div><dt>Guardian</dt><dd>{item.guardianName}</dd></div><div><dt>Contact</dt><dd>{item.guardianEmail}<br/>{item.guardianPhone}</dd></div><div><dt>Address</dt><dd>{item.address}, {item.postcode}</dd></div><div><dt>Submitted</dt><dd>{date(item.createdAt)}</dd></div></dl><div className="record-actions"><select aria-label={`Status for ${item.childName}`} value={item.status} disabled={busy===item.id||item.status==="enrolled"} onChange={e=>updateStatus(item.id,e.target.value)}><option value="new">New</option><option value="reviewing">Reviewing</option><option value="offered">Offered</option><option value="waitlisted">Waitlisted</option><option value="declined">Declined</option>{item.status==="enrolled"&&<option value="enrolled">Enrolled</option>}</select><button className="primary" disabled={item.status==="enrolled"||busy===item.id||classes.length===0} onClick={()=>{setEnrolError("");setSelected(item)}}>{item.status==="enrolled"?"Enrolled":busy===item.id?"Updating…":"Enrol child"}</button></div>{classes.length===0&&item.status!=="enrolled"&&<p className="action-hint">Create an available class before enrolling this child.</p>}<FormFeedback message={rowErrors[item.id]||""}/></article>)}</div>}
 {selected&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="enrol-child-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" type="button" onClick={closeEnrolment} disabled={busy===selected.id} aria-label="Close enrolment form"><X/></button><div className="modal-icon"><GraduationCap/></div><h2 id="enrol-child-title">Enrol {selected.childName}</h2><p>This creates the student and guardian records and assigns the child to a class.</p><FormFeedback id="enrol-feedback" message={enrolError}/><form onSubmit={enrol} onChange={()=>enrolError&&setEnrolError("")}><label>Class<select name="classId" aria-invalid={Boolean(enrolError)} aria-describedby={enrolError?"enrol-feedback":undefined} required defaultValue=""><option value="" disabled>Select an available class</option>{classes.map(c=><option key={c.id} value={c.id}>{c.name} ({c.enrolled}/{c.capacity})</option>)}</select></label><label>Guardian relationship<input name="relationship" defaultValue="Parent" required/></label><div className="modal-actions"><button className="secondary" type="button" onClick={closeEnrolment} disabled={busy===selected.id}>Cancel</button><button className="primary" disabled={busy===selected.id}>{busy===selected.id?"Enrolling child…":"Confirm enrolment"}</button></div></form></div></div>}
 </section>;
}

function StudentsView({query}:{query:string}){const [items,setItems]=useState<Student[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{api<{students:Student[]}>("/api/portal/students").then(r=>setItems(r.students)).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const filtered=items.filter(x=>!query||Object.values(x).join(" ").toLowerCase().includes(query.toLowerCase()));return <section className="panel live-records"><div className="records-toolbar"><div><h3>Students and guardians</h3><p>Live D1 records created through the enrolment workflow.</p></div></div>{error&&<ErrorNotice message={error}/>} {loading?<Loading/>:filtered.length===0?<Empty icon={GraduationCap} title="No enrolled students yet" text="Enrol an accepted application to create the first student record."/>:<div className="record-cards student-cards">{filtered.map(s=><article key={s.id}><div className="record-card-head"><div><span className="eyebrow">{s.admissionNumber}</span><h3>{s.fullName}</h3><p>{s.className||"Not assigned to a class"}</p></div><span className={`record-status status-${s.status}`}>{s.status}</span></div><dl><div><dt>Date of birth</dt><dd>{date(s.dateOfBirth)}</dd></div><div><dt>Gender</dt><dd>{s.gender||"—"}</dd></div><div><dt>Primary guardian</dt><dd>{s.guardianName||"—"}</dd></div><div><dt>Contact</dt><dd>{s.guardianEmail||"—"}<br/>{s.guardianPhone||""}</dd></div></dl></article>)}</div>}</section>}

function ClassesView({user,query}:{user:PortalUser;query:string}){
 const [items,setItems]=useState<ClassRecord[]>([]),[loading,setLoading]=useState(true),[pageError,setPageError]=useState(""),[formError,setFormError]=useState(""),[success,setSuccess]=useState(""),[showForm,setShowForm]=useState(false),[busy,setBusy]=useState(false);
 const load=useCallback(()=>{setLoading(true);setPageError("");api<{classes:ClassRecord[]}>("/api/portal/classes").then(r=>setItems(r.classes)).catch(e=>setPageError(e.message)).finally(()=>setLoading(false))},[]);
 useEffect(()=>{api<{classes:ClassRecord[]}>("/api/portal/classes").then(r=>setItems(r.classes)).catch(e=>setPageError(e.message)).finally(()=>setLoading(false))},[]);
 function closeForm(){if(busy)return;setShowForm(false);setFormError("")}
 function focusField(form:HTMLFormElement,name:string){requestAnimationFrame(()=>{const field=form.elements.namedItem(name);if(field instanceof HTMLElement)field.focus()})}
 async function create(event:FormEvent<HTMLFormElement>){
  event.preventDefault();const element=event.currentTarget;const form=new FormData(element);const start=String(form.get("startTime")||""),end=String(form.get("endTime")||"");
  if(end<=start){setFormError("End time must be later than the start time. Please correct the end time below.");focusField(element,"endTime");return}
  setBusy(true);setFormError("");
  try{await api("/api/portal/classes",{method:"POST",body:JSON.stringify(Object.fromEntries(form))});setShowForm(false);setSuccess("Class created successfully and is now available for enrolment.");window.setTimeout(()=>setSuccess(""),5000);load()}
  catch(e){const message=e instanceof Error?e.message:"Unable to create class.";setFormError(message);if(message.toLowerCase().includes("time"))focusField(element,"endTime")}
  finally{setBusy(false)}
 }
 const days=["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];const filtered=items.filter(x=>!query||Object.values(x).join(" ").toLowerCase().includes(query.toLowerCase()));
 return <section className="panel live-records"><div className="records-toolbar"><div><h3>Classes and capacity</h3><p>Manage available teaching groups and enrolment capacity.</p></div>{user.role==="admin"&&<button className="primary" onClick={()=>{setFormError("");setShowForm(true)}}><Plus size={16}/>Add class</button>}</div>{pageError&&<ErrorNotice message={pageError}/>}<FormFeedback message={success} tone="success"/>{loading?<Loading/>:filtered.length===0?<Empty icon={BookOpen} title="No classes created" text="Create a class before enrolling an accepted child."/>:<div className="class-cards">{filtered.map(c=><article key={c.id}><div><span className="eyebrow">{c.programme}</span><h3>{c.name}</h3><p>{days[c.dayOfWeek]} · {c.startTime}–{c.endTime}{c.room?` · ${c.room}`:""}</p></div><div className="capacity"><strong>{c.enrolled}/{c.capacity}</strong><span>enrolled</span><progress value={c.enrolled} max={c.capacity}/></div></article>)}</div>}
 {showForm&&<div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-labelledby="create-class-title" onMouseDown={e=>e.stopPropagation()}><button className="modal-close" type="button" onClick={closeForm} aria-label="Close class form"><X/></button><div className="modal-icon"><BookOpen/></div><h2 id="create-class-title">Create a class</h2><p>Add the teaching schedule and maximum number of pupils.</p><FormFeedback id="class-feedback" message={formError}/><form onSubmit={create} onChange={()=>formError&&setFormError("")}><label>Class name<input name="name" required placeholder="e.g. Qur’an Foundation A"/></label><label>Programme<input name="programme" required placeholder="e.g. Qur’an Foundation"/></label><div className="form-grid"><label>Day<select name="dayOfWeek" required defaultValue="6">{days.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><label>Room<input name="room" placeholder="Main Hall"/></label></div><div className="form-grid"><label>Start time<input name="startTime" type="time" required/></label><label>End time<input name="endTime" type="time" aria-invalid={Boolean(formError)} aria-describedby={formError?"class-feedback":undefined} required/></label></div><label>Capacity<input name="capacity" type="number" min="1" max="100" defaultValue="20" required/></label><div className="modal-actions"><button className="secondary" type="button" onClick={closeForm} disabled={busy}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving class…":"Create class"}</button></div></form></div></div>}
 </section>}
function NoAccess(){return <Empty icon={FileText} title="Administrator access required" text="Your account does not have permission to review admission applications."/>}
