"use client";
import { FormEvent,useState } from "react";
import { KeyRound,LockKeyhole } from "lucide-react";
import { FormFeedback } from "@/components/form-feedback";
import type { PortalUser } from "./auth-gate";
import { portalApi } from "./portal-api";
export function PasswordChange({user,onChanged,mandatory=false}:{user:PortalUser;onChanged:()=>Promise<void>;mandatory?:boolean}){
 const [error,setError]=useState(""),[busy,setBusy]=useState(false);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget),currentPassword=String(form.get("currentPassword")||""),newPassword=String(form.get("newPassword")||""),confirmation=String(form.get("confirmation")||"");if(newPassword!==confirmation){setError("The new passwords do not match.");return}if(currentPassword===newPassword){setError("Choose a new password that is different from the temporary or current password.");return}setBusy(true);setError("");try{await portalApi("/api/auth/change-password",{method:"POST",body:JSON.stringify({currentPassword,newPassword})});await onChanged()}catch(cause){setError(cause instanceof Error?cause.message:"Unable to change your password.")}finally{setBusy(false)}}
 const form=<div className={`password-change-card ${mandatory?"mandatory":""}`}><div className="modal-icon"><KeyRound/></div><h2>{mandatory?"Choose your own password":"Change password"}</h2><p>{mandatory?`Assalamu alaikum, ${user.fullName.split(" ")[0]}. Replace the temporary password before opening your workspace.`:"Update the password used for your Madrasah account. You will sign in again afterwards."}</p><FormFeedback id="password-change-error" message={error}/><form onSubmit={submit} onChange={()=>error&&setError("")}><label>Current password<span className="password-control"><LockKeyhole/><input name="currentPassword" type="password" autoComplete="current-password" required/></span></label><label>New password<span className="password-control"><LockKeyhole/><input name="newPassword" type="password" autoComplete="new-password" minLength={12} required/></span><small>At least 12 characters including uppercase, lowercase and a number.</small></label><label>Confirm new password<span className="password-control"><LockKeyhole/><input name="confirmation" type="password" autoComplete="new-password" minLength={12} required/></span></label><button className="primary" disabled={busy}>{busy?"Changing password…":"Save new password"}</button></form></div>;
 return mandatory?<main className="auth-page auth-page-simple"><section className="auth-showcase"><div className="auth-showcase-inner"><img className="auth-showcase-logo" src="/al-hidaya-logo.png" alt="Al-Hidaya Islamic Centre"/><span>Secure account setup</span><h1>Your private<br/>Madrasah workspace</h1><blockquote>“Indeed, Allah commands you to render trusts to whom they are due.”<cite>Qur’an 4:58</cite></blockquote></div></section><section className="auth-signin">{form}</section></main>:form;
}
