"use client";
import { useEffect,useState } from "react";
import { BarChart3,Download,RefreshCw } from "lucide-react";
import type { PortalUser } from "./auth-gate";
import { displayDate,money,portalApi } from "./portal-api";
type Report={activeStudents:number;activeClasses:number;attendance:Array<{date:string;present:number;late:number;absent:number;authorised:number}>;fees:{due:number;paid:number;outstanding:number;overdue:number;statuses:Array<{status:string;count:number}>};applications:Array<{status:string;count:number}>;role:string};
export function ReportsView({user}:{user:PortalUser}){
 const [report,setReport]=useState<Report|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
 function load(){setLoading(true);setError("");portalApi<Report>("/api/portal/reports").then(setReport).catch(cause=>setError(cause instanceof Error?cause.message:"Unable to load reports.")).finally(()=>setLoading(false))}
 useEffect(()=>{let active=true;portalApi<Report>("/api/portal/reports").then(result=>{if(active)setReport(result)}).catch(cause=>{if(active)setError(cause instanceof Error?cause.message:"Unable to load reports.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 if(user.role!=="admin"&&user.role!=="teacher"&&user.role!=="finance")return <div className="live-empty"><BarChart3/><h3>Staff access required</h3><p>Reports are not available for this account.</p></div>;
 return <section className="panel live-records operations-module"><div className="records-toolbar"><div><h3>Operational reports</h3><p>Live totals from D1 with downloadable records for authorised staff.</p></div><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button></div>{error&&<div className="live-error">{error}</div>}{loading?<div className="live-loading"><RefreshCw className="spin"/>Building reports…</div>:report&&<><div className="operations-stats"><article><span>Active pupils</span><strong>{report.activeStudents}</strong></article><article><span>Active classes</span><strong>{report.activeClasses}</strong></article>{(user.role==="admin"||user.role==="finance")&&<><article><span>Fees received</span><strong>{money(report.fees.paid)}</strong></article><article><span>Outstanding fees</span><strong>{money(report.fees.outstanding)}</strong></article></>}</div>
  <div className="report-grid"><article><div className="subsection-heading"><div><BarChart3/><span><strong>Attendance: last 30 days</strong><small>Daily saved attendance totals</small></span></div></div>{report.attendance.length===0?<p className="muted-copy">No attendance records in this period.</p>:<div className="report-table"><div className="report-tr report-th"><span>Date</span><span>Present</span><span>Late</span><span>Absent</span><span>Authorised</span></div>{report.attendance.map(row=><div className="report-tr" key={row.date}><span>{displayDate(row.date)}</span><span>{row.present}</span><span>{row.late}</span><span>{row.absent}</span><span>{row.authorised}</span></div>)}</div>}</article><article><div className="subsection-heading"><div><Download/><span><strong>Download data</strong><small>CSV files open in Excel</small></span></div></div><div className="download-list"><a className="secondary" href="/api/portal/reports?download=students"><Download/>Students report</a>{user.role!=="finance"&&<a className="secondary" href="/api/portal/reports?download=attendance"><Download/>Attendance report</a>}{(user.role==="admin"||user.role==="finance")&&<a className="secondary" href="/api/portal/reports?download=fees"><Download/>Fees report</a>}</div>{user.role==="admin"&&<div className="status-breakdown"><strong>Applications</strong>{report.applications.map(item=><p key={item.status}><span>{item.status}</span><b>{item.count}</b></p>)}</div>}</article></div></>}
 </section>
}
