"use client";
import { FormEvent,useCallback,useEffect,useState } from "react";
import { BookOpen,Plus,RefreshCw,ShieldCheck,UserRoundCheck,X } from "lucide-react";
import { FormFeedback } from "@/components/form-feedback";
import type { PortalUser } from "./auth-gate";
import { portalApi } from "./portal-api";
type Account={id:string;email:string;fullName:string;phone?:string;role:string;status:string;mustChangePassword:boolean;assignedClasses:number;guardianId?:string};
type Guardian={id:string;fullName:string;email:string;phone:string;children:string};
type ClassRecord={id:string;name:string;programme:string;teacherId?:string;teacherName?:string;active:number;enrolled:number};
export function StaffView({user,query}:{user:PortalUser;query:string}){
 const [accounts,setAccounts]=useState<Account[]>([]),[guardians,setGuardians]=useState<Guardian[]>([]),[classes,setClasses]=useState<ClassRecord[]>([]),[loading,setLoading]=useState(true),[pageError,setPageError]=useState(""),[formError,setFormError]=useState(""),[rowError,setRowError]=useState<Record<string,string>>({}),[success,setSuccess]=useState(""),[showForm,setShowForm]=useState(false),[role,setRole]=useState("teacher"),[busy,setBusy]=useState("");
 useEffect(()=>{if(!success)return;const timer=window.setTimeout(()=>setSuccess(""),5000);return()=>window.clearTimeout(timer)},[success]);
 const load=useCallback(()=>{setLoading(true);setPageError("");Promise.all([portalApi<{users:Account[];unlinkedGuardians:Guardian[]}>("/api/portal/users"),portalApi<{classes:ClassRecord[]}>("/api/portal/classes")]).then(([people,groups])=>{setAccounts(people.users);setGuardians(people.unlinkedGuardians);setClasses(groups.classes)}).catch(cause=>setPageError(cause instanceof Error?cause.message:"Unable to load accounts.")).finally(()=>setLoading(false))},[]);
 useEffect(()=>{let active=true;Promise.all([portalApi<{users:Account[];unlinkedGuardians:Guardian[]}>("/api/portal/users"),portalApi<{classes:ClassRecord[]}>("/api/portal/classes")]).then(([people,groups])=>{if(active){setAccounts(people.users);setGuardians(people.unlinkedGuardians);setClasses(groups.classes)}}).catch(cause=>{if(active)setPageError(cause instanceof Error?cause.message:"Unable to load accounts.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 async function createAccount(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy("create");setFormError("");try{const result=await portalApi<{email:string;role:string}>("/api/portal/users",{method:"POST",body:JSON.stringify(Object.fromEntries(form))});setShowForm(false);setSuccess(`${result.role.charAt(0).toUpperCase()+result.role.slice(1)} account created for ${result.email}. The temporary password must be changed at first sign-in.`);load()}catch(cause){setFormError(cause instanceof Error?cause.message:"Unable to create the account.")}finally{setBusy("")}}
 async function changeStatus(account:Account){setBusy(account.id);setRowError(value=>({...value,[account.id]:""}));const status=account.status==="active"?"disabled":"active";try{await portalApi(`/api/portal/users/${account.id}`,{method:"PATCH",body:JSON.stringify({status})});setAccounts(current=>current.map(item=>item.id===account.id?{...item,status}:item));setSuccess(`${account.fullName}'s account is now ${status}.`)}catch(cause){setRowError(value=>({...value,[account.id]:cause instanceof Error?cause.message:"Unable to update the account."}))}finally{setBusy("")}}
 async function assignTeacher(classId:string,teacherId:string){setBusy(classId);setRowError(value=>({...value,[classId]:""}));const previousTeacherId=classes.find(item=>item.id===classId)?.teacherId||"";try{await portalApi(`/api/portal/classes/${classId}`,{method:"PATCH",body:JSON.stringify({teacherId})});const teacher=accounts.find(item=>item.id===teacherId);setClasses(current=>current.map(item=>item.id===classId?{...item,teacherId:teacherId||undefined,teacherName:teacher?.fullName}:item));setAccounts(current=>current.map(account=>{const adjustment=(account.id===teacherId?1:0)-(account.id===previousTeacherId?1:0);return adjustment?{...account,assignedClasses:Math.max(0,Number(account.assignedClasses||0)+adjustment)}:account}));setSuccess(teacher?`${teacher.fullName} was assigned to the class.`:"The class is now unassigned.")}catch(cause){setRowError(value=>({...value,[classId]:cause instanceof Error?cause.message:"Unable to assign the teacher."}))}finally{setBusy("")}}
 if(user.role!=="admin")return <div className="live-empty"><ShieldCheck/><h3>Administrator access required</h3><p>Only administrators can manage user accounts and class assignments.</p></div>;
 const filtered=accounts.filter(item=>!query||`${item.fullName} ${item.email} ${item.role} ${item.status}`.toLowerCase().includes(query.toLowerCase())),teachers=accounts.filter(item=>item.role==="teacher"&&item.status==="active");
 return <section className="panel live-records operations-module"><div className="records-toolbar"><div><h3>Staff and portal accounts</h3><p>Create secure accounts and assign active teachers to classes.</p></div><div className="toolbar-actions"><button className="secondary" onClick={load}><RefreshCw size={16}/>Refresh</button><button className="primary" onClick={()=>{setRole("teacher");setFormError("");setShowForm(true)}}><Plus size={16}/>New account</button></div></div>{pageError&&<div className="live-error">{pageError}</div>}<FormFeedback message={success} tone="success"/>
  {loading?<div className="live-loading"><RefreshCw className="spin"/>Loading accounts…</div>:<><div className="operation-cards account-cards">{filtered.map(account=><article key={account.id}><div className="operation-card-head"><div><span className="eyebrow">{account.role}</span><h3>{account.fullName}</h3><p>{account.email}{account.phone?` · ${account.phone}`:""}</p></div><span className={`record-status status-${account.status}`}>{account.status}</span></div><dl><div><dt>Security</dt><dd>{account.mustChangePassword?"Password change required":"Password established"}</dd></div><div><dt>Assigned classes</dt><dd>{account.role==="teacher"?account.assignedClasses:"—"}</dd></div></dl>{account.id!==user.id&&<button className="secondary card-action" disabled={busy===account.id} onClick={()=>changeStatus(account)}>{account.status==="active"?"Disable account":"Reactivate account"}</button>}<FormFeedback message={rowError[account.id]||""}/></article>)}</div>
   <div className="subsection-heading"><div><BookOpen/><span><strong>Teacher assignments</strong><small>Teachers only see pupils and registers for assigned classes.</small></span></div></div><div className="assignment-list">{classes.map(group=><div key={group.id}><span><strong>{group.name}</strong><small>{group.programme} · {group.enrolled} enrolled</small></span><select value={group.teacherId||""} disabled={busy===group.id} onChange={event=>assignTeacher(group.id,event.target.value)} aria-label={`Teacher for ${group.name}`}><option value="">Unassigned</option>{teachers.map(teacher=><option key={teacher.id} value={teacher.id}>{teacher.fullName}</option>)}</select><FormFeedback message={rowError[group.id]||""}/></div>)}</div></>}
  {showForm&&<div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={()=>!busy&&setShowForm(false)} disabled={Boolean(busy)} aria-label="Close account form"><X/></button><div className="modal-icon"><UserRoundCheck/></div><h2>Create portal account</h2><p>The user signs in with email and a temporary password, then must choose a new password immediately.</p><FormFeedback id="account-form-error" message={formError}/><form onSubmit={createAccount} onChange={()=>formError&&setFormError("")}><label>Account role<select name="role" value={role} onChange={event=>setRole(event.target.value)}><option value="teacher">Teacher</option><option value="finance">Finance staff</option><option value="parent">Parent or guardian</option><option value="admin">Administrator</option></select></label>{role==="parent"&&<label>Guardian record<select name="guardianId" required defaultValue=""><option value="" disabled>Select a guardian without an account</option>{guardians.map(guardian=><option key={guardian.id} value={guardian.id}>{guardian.fullName} · {guardian.children||guardian.email}</option>)}</select></label>}<label>Full name<input name="fullName" required/></label><div className="form-grid"><label>Email address<input name="email" type="email" autoComplete="off" required/></label><label>Telephone<input name="phone" type="tel" autoComplete="off"/></label></div><label>Temporary password<input name="password" type="password" autoComplete="new-password" minLength={12} required/><small>At least 12 characters with uppercase, lowercase and a number.</small></label><div className="modal-actions"><button className="secondary" type="button" onClick={()=>setShowForm(false)} disabled={Boolean(busy)}>Cancel</button><button className="primary" disabled={Boolean(busy)}>{busy?"Creating…":"Create account"}</button></div></form></div></div>}
 </section>
}
